<a href="https://colab.research.google.com/github/imamahasane/TensorFlow_2.0/blob/main/Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

In [2]:
 string = tf.Variable("Imam Ahasan", tf.string)
 number = tf.Variable(324, tf.int16)
 floating = tf.Variable(3.242, tf.float64)

# Rank / Degree of Tensors

In [5]:
r1_tensor = tf.Variable(["Test"], tf.string)
r2_tensor = tf.Variable([["Test", "Ok"], ["Imam", "Onik"]], tf.string)

In [6]:
tf.rank(r1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
tf.rank(r2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensor

In [8]:
r1_tensor.shape

TensorShape([1])

In [9]:
r2_tensor.shape

TensorShape([2, 2])

# Changing Shape

In [16]:
t1 = tf.ones([1, 2, 3])
t2 = tf.reshape(t1, [3, 2, 1])
t3 = tf.reshape(t2, [2, -1])

In [18]:
print(t1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [19]:
print(t2)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


In [20]:
print(t3)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
